#!/bin/bash 


if [[ $EUID -ne 0 ]]; then
  echo "Execute with root."
  exit 1
fi

read -p "Username: " username
if [[ "$username" == "" ]]; then
  username="tomasdada"
fi
read -p "Password: " password

touch tdh.conf

echo "username_c=$username" >> tdh.conf
echo "servername_c=$servername" >> tdh.conf

echo "Config set."

mv .tdh /home
mv tdh.conf .tdh.conf
mv .tdh.conf /home

echo "sudo /home/.tdh" >> /home/${username}/.profile
echo "Setup complete."
rm -- "$0"
